### ISSUE TITLE
Colour Changer Website

### ISSUE THREAD

**Issue by GeekNerds** [GeekNerds/Hacktoberfest-2022#1]
Colour Changer Website

- Design a website with a button at center 
![image](https://user-images.githubusercontent.com/114431950/192360391-2212f06e-fa2c-4941-a27e-66388d674543.png)

- when click on button background change
![image](https://user-images.githubusercontent.com/114431950/192360536-789cb784-d9f4-440b-99e5-5bf2d8d2b509.png)
![image](https://user-images.githubusercontent.com/114431950/192360593-2c0255d1-afc7-4fa5-8902-0c6b9c3ff008.png)

**Comment by laxmanbalaraman** [comment]
Hey @GeekNerds ! I would like to work on this one. can you assign this to me?
