### ISSUE TITLE
Pokémon Website

### ISSUE THREAD

**Issue by GeekNerds** [GeekNerds/Hacktoberfest-2022#2]
*Pokémon Website

- Make a prokemon website using API fetch
- https://pokeapi.co
  Using this website API
![image](https://user-images.githubusercontent.com/114431950/192361477-0b49590e-96df-402d-beb1-a62b77a32d3e.png)

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by manav-06** [comment]
Hi. This seems interesting. Can you assign it to me?

**Comment by GeekNerds** [comment]
@manav-06 @codegoggins No need to asign you can contribute
