### ISSUE TITLE
BMI Calaculator

### ISSUE THREAD

**Issue by GeekNerds** [GeekNerds/Hacktoberfest-2022#4]
**BMI Calculator**

- Make a bmi calculator using HTML CSS JS

![image](https://user-images.githubusercontent.com/114431950/192362826-e11a8ad7-69b7-4b3d-b9c2-1eae891f7773.png)

**Comment by Nandinisaagar** [comment]
Hey! 
I would like to contribute in this project, please assign it to me.

**Comment by sumedhav2004** [comment]
Hi there!
I would love to work on this. Please assign it to me.

**Comment by GeekNerds** [comment]
Hi, @sumedhav2004 you can proceed and make your contribution
