### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by GeekNerds** [GeekNerds/Hacktoberfest-2022#49]
Implement Bubble Sort in C++, JAVA or Python

No need to assign, you can contribute.

**Comment by nitingarg2207** [comment]
Hey @GeekNerds please assign this to me.

**Comment by haris-bit** [comment]
ok, contributing. Please accept mine. 🙂

**Comment by Debangshu97** [comment]
hey @GeekNerds I want to contribute too

**Comment by manojku1803** [comment]
Hey @GeekNerds I want to contribute in this

**Comment by GeekNerds** [comment]
@haris-bit @Debangshu97 @nitingarg2207 @manojku1803 no need to assign, just contribute.
