### ISSUE TITLE
BMI Calculator  React JS

### ISSUE THREAD

**Issue by GeekNerds** [GeekNerds/Hacktoberfest-2022#5]
**BMI Calculator**

- Make a bmi calculator using HTML CSS JS

![image](https://user-images.githubusercontent.com/114431950/192362826-e11a8ad7-69b7-4b3d-b9c2-1eae891f7773.png)

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by Nandinisaagar** [comment]
Hey!
I would like to contribute in this project, please assign it to me.
