### ISSUE TITLE
Want to add educational website

### ISSUE THREAD

**Issue by vedsom** [GeekNerds/Hacktoberfest-2022#64]
@GeekNerds Want to build a platform where all types of content blog, courses and YouTube tutorial of any particular skills. So users can save their time.

**Comment by GeekNerds** [comment]
@vedsom Great idea, we are very happy to make this project

**Comment by vedsom** [comment]
> @vedsom Great idea, we are very happy to make this project

@GeekNerds thanx. So can you assign me this issue, so that i can start working..
