### ISSUE TITLE
Notes App 

### ISSUE THREAD

**Issue by Swap-nil-2003** [GeekNerds/Hacktoberfest-2022#69]
I would like to contribute a Notes App built with HTML, CSS ad and Javascript.

**Comment by GeekNerds** [comment]
@Swap-nil-2003 You can contribute

**Comment by srini-vasan-c** [comment]
@Swap-nil-2003 if any contribution still need, pls assign to me. I would like to contribute.

**Comment by GeekNerds** [comment]
@Swap-nil-2003 I have merged, the PR. If anything should be added I will let you know

**Comment by Swap-nil-2003** [comment]
Cool thanks 👍
