### ISSUE TITLE
I want to contribute 2048 game in python.(Console version)

### ISSUE THREAD

**Issue by chaitanyasai321** [GeekNerds/Hacktoberfest-2022#86]
Can you please Assign me an issue. I want to contribute 2048 game in python.(Console version)

**Comment by GeekNerds** [comment]
@chaitanyasai321 you can proceed and make your contribution.

**Comment by chaitanyasai321** [comment]
PR for 2048 Game https://github.com/GeekNerds/Hacktoberfest-2022/pull/87
Do consider this!!
    Thankyou
